spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/cadastro?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${MYSQL_USER:cadastro}
spring.datasource.password=${MYSQL_PASSWORD:cadastro}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
